# Game Architecture Workflow Configuration
name: game-architecture
description: "Collaborative game architecture workflow for AI-agent consistency. Intelligent, adaptive conversation that produces a decision-focused game architecture document covering engine, systems, networking, and technical design optimized for game development."
author: "BMad"

# Critical variables
config_source: "{project-root}/.bmad/bmgd/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
game_dev_experience: "{config_source}:game_dev_experience"
date: system-generated

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
input_file_patterns:
  gdd:
    description: "Game Design Document with mechanics and systems"
    whole: "{output_folder}/*gdd*.md"
    sharded: "{output_folder}/*gdd*/index.md"
    load_strategy: "INDEX_GUIDED"

  epics:
    description: "Epic definitions with user stories"
    whole: "{output_folder}/*epic*.md"
    sharded: "{output_folder}/*epic*/index.md"
    load_strategy: "FULL_LOAD"

  narrative:
    description: "Narrative design with story and characters (optional)"
    whole: "{output_folder}/*narrative*.md"
    sharded: "{output_folder}/*narrative*/index.md"
    load_strategy: "INDEX_GUIDED"

  document_project:
    description: "Brownfield project documentation (optional)"
    sharded: "{output_folder}/index.md"
    load_strategy: "INDEX_GUIDED"

# Module path and component files
installed_path: "{project-root}/.bmad/bmgd/workflows/3-technical/game-architecture"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
template: "{installed_path}/architecture-template.md"

# Knowledge bases for intelligent decision making
decision_catalog: "{installed_path}/decision-catalog.yaml"
architecture_patterns: "{installed_path}/architecture-patterns.yaml"
pattern_categories: "{installed_path}/pattern-categories.csv"

# Output configuration
default_output_file: "{output_folder}/game-architecture.md"

# Workflow metadata
version: "1.3.2"
replaces: "architecture"
paradigm: "facilitation-driven"
execution_time: "30-90 minutes depending on user skill level"
features:
  - "Starter template discovery and integration"
  - "Dynamic version verification via web search"
  - "Adaptive facilitation by skill level"
  - "Decision-focused architecture"
  - "Novel pattern design for unique concepts"
  - "Intelligent pattern identification - LLM figures out what patterns matter"
  - "Implementation patterns for agent consistency"

standalone: true
