# Product Brief - Interactive Workflow Configuration
name: product-brief
description: "Interactive product brief creation workflow that guides users through defining their product vision with multiple input sources and conversational collaboration"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Optional input documents
recommended_inputs:
  - market_research: "Market research document (optional)"
  - brainstorming_results: "Brainstorming session outputs (optional)"
  - competitive_analysis: "Competitive analysis (optional)"
  - initial_ideas: "Initial product ideas or notes (optional)"

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
input_file_patterns:
  research:
    whole: "{output_folder}/*research*.md"
    sharded: "{output_folder}/*research*/index.md"

  brainstorming:
    whole: "{output_folder}/*brainstorm*.md"
    sharded: "{output_folder}/*brainstorm*/index.md"

  document_project:
    sharded: "{output_folder}/docs/index.md"

# Module path and component files
installed_path: "{project-root}/bmad/bmm/workflows/1-analysis/product-brief"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration
default_output_file: "{output_folder}/product-brief-{{project_name}}-{{date}}.md"

standalone: true
