# Create UX Design Workflow Configuration
name: create-ux-design
description: "Collaborative UX design facilitation workflow that creates exceptional user experiences through visual exploration and informed decision-making. Unlike template-driven approaches, this workflow facilitates discovery, generates visual options, and collaboratively designs the UX with the user at every step."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Input requirements - We work from PRD, Brief, or Brainstorming docs
recommended_inputs:
  - prd: "Product Requirements Document with features and user journeys"
  - product_brief: "Product brief with vision and target users"
  - brainstorming: "Brainstorming documents with ideas and concepts"

# Input file references (fuzzy matched from output folder)
prd_file: "{output_folder}/bmm-PRD.md or PRD.md or product-requirements.md"
brief_file: "{output_folder}/product-brief.md or brief.md or project-brief.md"
brainstorm_file: "{output_folder}/brainstorming.md or brainstorm.md or ideation.md"

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
input_file_patterns:
  prd:
    whole: "{output_folder}/*prd*.md"
    sharded: "{output_folder}/*prd*/index.md"

  product_brief:
    whole: "{output_folder}/*brief*.md"
    sharded: "{output_folder}/*brief*/index.md"

  epics:
    whole: "{output_folder}/*epic*.md"
    sharded: "{output_folder}/*epic*/index.md"

  brainstorming:
    whole: "{output_folder}/*brainstorm*.md"
    sharded: "{output_folder}/*brainstorm*/index.md"

  document_project:
    sharded: "{output_folder}/docs/index.md"

# Module path and component files
installed_path: "{project-root}/bmad/bmm/workflows/2-plan-workflows/create-ux-design"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
template: "{installed_path}/ux-design-template.md"

# Output configuration - Progressive saves throughout workflow
default_output_file: "{output_folder}/ux-design-specification.md"
color_themes_html: "{output_folder}/ux-color-themes.html"
design_directions_html: "{output_folder}/ux-design-directions.html"

standalone: true

# Web bundle configuration for standalone deployment